
apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-loan-app
  
# Specification of the desired behavour of the deployment
spec:
  selector:
    matchLabels:
      app: ai-loan-app

  replicas: 2
  
  template:
    metadata:

      labels:
        app: ai-loan-app
    spec:
     
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - command:
            [
              "/bin/bash",
              "-c",
              "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000",
            ]
          
          name: ai-loan-app
          # define the image to pull
          image: registry.git.chalmers.se/courses/dit826/2023/group6/group6:latest
          # Always pull the image from the registry when the
          # manifest is applied.
          imagePullPolicy: Always
          # Limits the resourced dedicated to the container.
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
         
---

apiVersion: v1
kind: Service

metadata:
  name: ai-loan-app
  labels:
    app: ai-loan-app

spec:
  type: LoadBalancer
  loadBalancerIP: 34.88.187.253
  ports:
    - port: 3000
      targetPort: 8000
  selector:
    app: ai-loan-app