# Generated by Django 4.2.8 on 2023-12-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loanApp", "0004_applicant_loan_id_alter_applicant_risk_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("file_path", models.CharField(max_length=255)),
            ],
        ),
    ]
