# Generated by Django 4.2.7 on 2023-12-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loanApp", "0005_savedmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="profile"),
        ),
    ]
