# Generated by Django 4.2.8 on 2023-12-16 18:10

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):
    dependencies = [
        ("loanApp", "0010_alter_customuser_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplicant",
            fields=[
                (
                    "LoanID",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Age", models.IntegerField()),
                ("Income", models.FloatField()),
                ("LoanAmount", models.FloatField()),
                ("CreditScore", models.IntegerField()),
                ("MonthsEmployed", models.IntegerField()),
                ("LoanTerm", models.IntegerField()),
                ("DTIRatio", models.FloatField()),
                ("EmploymentType", models.CharField(max_length=50)),
                ("Default", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
